name: Pipeline

on:
  push:
    tags:
      - 'v*'
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  pipeline:
    name: Build and Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        libs:
          - storybook-addon-badges

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set env.TAG
        if: ${{ github.ref_type == 'tag' }}
        run: echo "TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - uses: actions/cache@v2
        id: cache
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn install --non-interactive

      - name: Lint - ${{ matrix.libs }}
        run: yarn nx lint ${{ matrix.libs }}

      - name: Unit Test - ${{ matrix.libs }}
        run: yarn nx test ${{ matrix.libs }} --codeCoverage

      - name: Build Library - ${{ matrix.libs }}
        run: yarn nx build ${{ matrix.libs }}

      - name: Post test coverage - ${{ matrix.libs}}
        if: ${{ failure() }}
        uses: romeovs/lcov-reporter-action@v0.2.16
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          lcov-file: ./coverage/libs/${{ matrix.libs }}/lcov.info

      - name: Yarn Add Library - ${{ matrix.libs }}
        run: yarn add ./dist/libs/${{ matrix.libs }}

      - name: Build Storybook
        run: yarn nx run geometricpanda:build-storybook

      - name: Yarn Remove Library - ${{ matrix.libs }}
        run: yarn remove @geometricpanda/${{ matrix.libs }}

      - name: Deploy Docs 🚀
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist/storybook/geometricpanda
          CLEAN: true

      - name: Ensure package.json version matches tag - ${{ matrix.libs}}
        if: ${{ github.ref_type == 'tag' }}
        run: npm version ${{ env.TAG }} --prefix ./libs/${{ matrix.libs}} --allow-same-version

      - name: Release Package - ${{ matrix.libs }}
        if: ${{ github.ref_type == 'tag' }}
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: ./dist/libs/${{ matrix.libs }}/package.json
          check-version: true
